FROM node:16-alpine3.11 AS node

FROM node AS builder

ARG APP_API_URI
ARG APP_BRAND
ARG APP_DASHBOARD_YEARS
ARG APP_HISTORY_YEARS
ARG APP_PROCESS_YEARS
ARG APP_SEARCH_DEBOUNCE_MS
ARG APP_PROPERTY_BALANCE_THRESHOLD
ARG APP_EMAIL_BATCH_LIMIT_MAX

WORKDIR /app

COPY package*.json ./
RUN npm install --silent

COPY . ./
RUN echo "REACT_APP_API_URI=$APP_API_URI" >> .env
RUN echo "REACT_APP_BRAND=$APP_BRAND" >> .env
RUN echo "REACT_APP_DASHBOARD_YEARS=$APP_DASHBOARD_YEARS" >> .env
RUN echo "REACT_APP_HISTORY_YEARS=$APP_HISTORY_YEARS" >> .env
RUN echo "REACT_APP_PROCESS_YEARS=$APP_PROCESS_YEARS" >> .env
RUN echo "REACT_APP_SEARCH_DEBOUNCE_MS=$APP_SEARCH_DEBOUNCE_MS" >> .env
RUN echo "REACT_APP_PROPERTY_BALANCE_THRESHOLD=$APP_PROPERTY_BALANCE_THRESHOLD" >> .env
RUN echo "REACT_APP_EMAIL_BATCH_LIMIT_MAX=$APP_EMAIL_BATCH_LIMIT_MAX" >> .env
RUN npm run build

FROM nginx:alpine AS final
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]