/* Generated by restful-react */

import React from "react";
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from "restful-react";
export const SPEC_VERSION = "1.0.0"; 
export interface Profile {
  id: number;
  name: string;
  username: string;
  password?: string;
  scopes?: string;
}

export interface AuthResult {
  profile: Profile;
  token: string;
}

export type AuthProps = Omit<MutateProps<AuthResult, unknown, void, void, void>, "path" | "verb">;

export const Auth = (props: AuthProps) => (
  <Mutate<AuthResult, unknown, void, void, void>
    verb="POST"
    path={`/api/profile/auth`}
    
    {...props}
  />
);

export type UseAuthProps = Omit<UseMutateProps<AuthResult, unknown, void, void, void>, "path" | "verb">;

export const useAuth = (props: UseAuthProps) => useMutate<AuthResult, unknown, void, void, void>("POST", `/api/profile/auth`, props);


export type MeProps = Omit<GetProps<Profile, unknown, void, void>, "path">;

export const Me = (props: MeProps) => (
  <Get<Profile, unknown, void, void>
    path={`/api/profile/me`}
    
    {...props}
  />
);

export type UseMeProps = Omit<UseGetProps<Profile, unknown, void, void>, "path">;

export const useMe = (props: UseMeProps) => useGet<Profile, unknown, void, void>(`/api/profile/me`, props);

